### ISSUE TITLE
Agent types

### ISSUE THREAD

**Issue by ghost** [michalusio/AUM-Project-Village#4]
We decided that the main types are going to be:
 1. A scavenger
    - main action: finding food
    - secondary action: moving food to stockpile
 2. A farmer
    - main action: sowing fields
    - secondary action: harvesting fields
 3. A baker
    - main action: baking bread from wheat
    - secondary action: moving bread to stockpile

**Comment by michalusio** [comment]
We should have roles that generate food on the basic level (finite resource), something that generates less food than basic, and something that will generate more food from the second type. It will force the villagers to switch from the first to a balanced economy of second and third.

**Comment by michalusio** [comment]
We can also create more types, but these are the basic ones we need.
